on: push

jobs:
    secrets:
        runs-on: unbuntu-latest
        steps:
        - run: | 
           import os
           print(len(os.getenv('MY_VAR')))
          shell: python
          env: 
            MY_VAR: ${{ secrets.WBSECRET }}
